---

pipelines:
  browser:
    - accepts
    - setLocale

  api:
    - accepts
    - setLocale

scopes:
  - path: '/api'
    pipeline: browser
    routes:
      - resources: users

  - path: '/'
    pipeline: browser
    routes:
      - resources:
          name: users
          only: ['show']

      - resource:
          name: session
          except: ['new']
          routes:
            - resources: tokens

      - resources:
          name: articles
          routes:
            - resources: comments
            - resource:
                name: metadata
                except: ['show']
