setup: install migrate

migrate:
	npx nodos db migrate

install:
	npm install

lint:
	npx eslint

start:
	DEBUG=nodos:* npm start

nodos:
	DEBUG=nodos:* npx nodos

nodos-routes:
	DEBUG=nodos:* npx nodos routes

nodos-console:
	DEBUG=nodos:* npx nodos console

test:
	DEBUG=nodos:* npm test
